
services:
  tomcat:
    image: tomcat:11-jdk17-temurin
    container_name: tomcat11
    ports:
      - "8080:8080"
    volumes:
      - ./war/:/usr/local/tomcat/webapps/
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom
